name: GitHub-Profile-3D-Contrib

on:
  schedule: # 매일 UTC 18:00 (한국 시간 새벽 3시)에 실행
    - cron: "0 18 * * *"
  workflow_dispatch: # 수동 실행을 허용

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389101/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }} # 당신의 GitHub 사용자 이름이 자동으로 들어갑니다.
          # THEME: night-rainbow (이전에 설정한 테마입니다.)
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated 3D contribution map"
          git push
